const SIX_HOURS_MS = 6 * 60 * 60 * 1000;

/** Rotates every 6 hours (same quote for everyone on the same device clock window). */
export const MOTIVATIONAL_QUOTES: readonly string[] = [
  "Discipline is choosing between what you want now and what you want most.",
  "Every day is a chance to be better than yesterday.",
  "Lock in. No distractions. No excuses.",
  "The pain of discipline is far less than the pain of regret.",
  "Your future self is watching you right now.",
  "Consistency beats intensity every time.",
  "Work in silence. Let results make the noise.",
  "You don't rise to the level of your goals, you fall to the level of your systems.",
  "Small wins, daily. That's the formula.",
  "The grind never stops. Nor should you.",
  "Show up when you don't feel like it — that's the whole game.",
  "One focused hour beats a distracted day.",
  "Boredom is the price of mastery. Pay it gladly.",
  "Your habits are voting for the person you're becoming.",
  "Energy flows where attention goes.",
  "Do the hard thing first; the day gets easier.",
  "Progress is quiet until it isn't.",
  "You owe yourself the effort, not the outcome.",
  "Stack days, not excuses.",
  "The scoreboard is private until the work is public.",
  "Deep work is a superpower most people refuse to unlock.",
  "Protect your mornings like they are non‑renewable.",
  "If it's important, schedule it. If it's not, delete it.",
  "Intensity fades; systems stay.",
  "You can't cheat the reps.",
  "The calendar never lies about priorities.",
  "Be harder to distract than the average person is to entertain.",
  "Ship the small version. Improve tomorrow.",
  "Comfort is a slow thief.",
  "Discipline is remembering what you want.",
  "The best time to start was yesterday. The second best is now.",
  "Let your actions be louder than your intentions.",
  "One rep closer.",
  "You are not your mood; you are your choices.",
  "Focus is saying no a thousand times.",
  "The work doesn't care about your feelings — show up anyway.",
  "Earn your rest.",
  "Make the next hour undeniable.",
  "Attention is your scarcest asset. Spend it wisely.",
  "Average is easy. You didn't pick easy.",
  "Turn notifications off. Turn your life on.",
  "The shortcut is the longcut.",
  "Be the person who finishes.",
  "Momentum is built, not found.",
  "Your standards create your ceiling.",
  "Do it tired. Do it unsure. Do it anyway.",
  "The only bad workout is the one that didn't happen.",
  "Read when it's easier to scroll.",
  "Pray when it's easier to worry.",
  "Study when it's easier to quit.",
  "Silence your phone. Amplify your life.",
  "You can't think your way into right acting — act your way into right thinking.",
  "The room gets brighter when you stop dimming yourself.",
  "Win the hour, win the day.",
  "Replace 'I should' with 'I did'.",
  "If you're consistent, you're already rare.",
  "The goal is not to be busy; the goal is to be effective.",
  "Let 'no' be a complete sentence.",
  "Protect deep work like a meeting with your CEO — because you are.",
  "You don't need more time. You need fewer leaks.",
  "Be allergic to average.",
  "The mirror rewards honesty.",
  "One day or day one. You decide.",
  "Your reputation follows your patterns.",
  "Make it boring on purpose — boring is reliable.",
  "The work is the way out.",
  "Stop negotiating with yourself.",
  "If it matters, it's measured.",
  "You can't outsource ownership.",
  "Let consistency be your flex.",
  "The best plan is the one you execute.",
  "Do the boring fundamentals until they look elite.",
  "You are building in the dark. Keep building.",
  "The world isn't against you; it's indifferent — be for yourself.",
  "Trade dopamine for dopamine you earned.",
  "Make the next decision a proud one.",
  "You don't need motivation; you need a standard.",
  "Let your calendar reflect your values.",
  "Be harder to break than yesterday.",
  "The pain ends; the pride stays.",
  "You can't microwave mastery.",
  "Keep promises to yourself — that's self‑respect.",
  "If you're tired, rest — then return.",
  "The smallest step forward is still forward.",
  "Let discipline feel like freedom.",
  "You are allowed to be tired. You are not allowed to quit.",
  "Stack evidence that you are serious.",
  "Make your future self proud in the next 25 minutes.",
  "The only competition that matters is yesterday's you.",
  "Be the thermostat, not the thermometer.",
  "Let your 'yes' be rare and powerful.",
  "You don't rise on inspiration; you rise on reps.",
  "Turn pressure into polish.",
  "If you want uncommon results, live uncommon hours.",
  "The work is not optional for the life you want.",
  "Be impatient with excuses and patient with results.",
  "Let your effort be obvious.",
  "You can't buy integrity at a discount.",
  "Make rest earned, not stolen.",
  "The next rep builds the next you.",
  "Be allergic to 'I'll start Monday.'",
  "If you can do it for a day, you can train it into a week.",
  "Let your habits be a love letter to your goals.",
  "You are not behind; you are on your own clock — just move.",
  "The best revenge is a body of work.",
  "Make focus your default state.",
  "You don't need perfect conditions — you need a start.",
  "Let your discipline be louder than your doubts.",
  "The score takes care of itself when the process is honest.",
  "Be the kind of person who does what they said they would.",
  "If it's easy, it's probably not the work.",
  "Let your output age you into credibility.",
  "You can't cheat the clock — but you can respect it.",
  "Make today undeniable.",
  "The path is the prize.",
  "Be harder to stop than the resistance is loud.",
  "If you want peace, pay the price of preparation.",
  "Let your standards rise faster than your mood.",
  "You are one session away from momentum.",
  "The work is the shortcut.",
  "Make your 'later' smaller every day.",
  "Be the proof.",
  "Lock in again — same conviction, new reps.",
  "Let boredom become your training partner.",
  "The next hour can change the narrative.",
  "Make discipline your default aesthetic.",
  "If you stay ready, you don't have to get ready.",
  "Let your effort compound in public silence.",
  "The smallest promise kept changes your identity.",
  "Be impossible to ignore — through consistency.",
  "Turn 'I wish' into 'I will' with one action.",
  "Your attention is a vote — vote for your future.",
  "Let the work be non‑negotiable.",
  "Make the hard thing the first thing.",
  "You are not too late; you are right on time to start.",
  "Let today be evidence.",
];

export function getRotatingQuote(): string {
  const slot = Math.floor(Date.now() / SIX_HOURS_MS);
  return MOTIVATIONAL_QUOTES[slot % MOTIVATIONAL_QUOTES.length]!;
}
